apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: application
spec:
  selector:
    app: hello-app
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer