apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: ahmedgamal22/simpleapp
        ports:
        - containerPort: 4000